replicaCount: 1

image:
  repository: thomasschilder/dvre-asset-api
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

livenessProbe:
  httpGet:
    path: /api/health
    port: http
readinessProbe:
  httpGet:
    path: /api/health
    port: http

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

env:
  PG_HOST: ""
  PG_PORT: ""
  PG_USER: ""
  PG_DATABASE: ""
  API_PORT: ""

secrets:
  PG_PASSWORD: ""
