apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dvre-asset-indexer.fullname" . }}
  labels:
    {{- include "dvre-asset-indexer.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_PASSWORD: {{ .Values.secrets.PG_PASSWORD | quote }}
