apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: blockscout
---
apiVersion: v1
kind: Namespace
metadata:
  name: asset-indexer